### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ryarom148** [0zean/Temporal-Attention-time-series-analysis#1]
Good afternoon! Thank you for your great insight and work.
I have a question about the preparation of train and test set.
1) is it correct :?
   lbls_train = lbls_train.iloc[:-n_past] not  lbls_train = lbls_train.iloc[n_past:]
   ( looks like you apply future values to the history
2) when preparing the test data, is it specific logic that you add n_past steps of zeros to the test features, and remove the  n_past steps from labels at the beginning:
 pred2 = pred2[n_past:]. it looks like that because of this logic,
there is a shift of futures values to the past.
once again, thank you for your great work.

**Comment by LinuxpowerLudo** [comment]
Hello,
I play with the code since some days .. and i have the same feedback that ryarom148 !!

@ryarom148  or @Nicholas-Picini have you fix the problem ? 

Thx 
Regards.

**Comment by ryarom148** [comment]
> Hello,
> I play with the code since some days .. and i have the same feedback that ryarom148 !!
> 
> @ryarom148 or @Nicholas-Picini have you fix the problem ?
> 
> Thx
> Regards.
 I fixed they way it should be, but prediction is very bad. model doesn’t work for me.

**Comment by LinuxpowerLudo** [comment]
Ok thanks, I'm coming to the same conclusion ! Too bad.

**Comment by Nicholas-Picini** [comment]
Firstly, apologies for not responding to your original question @ryarom148 for some reason I have not been receiving notification for issues on my repos. 

You are right, lbls_train.iloc[n_past:] is the correct notation but this introduces another problem because the labels are now incorrectly aligned with the X_train matrix. I will rework the tabl.py code and update the repository when finished.

**Comment by lorrp1** [comment]
@ryarom148 @LinuxpowerLudo @Nicholas-Picini 
Have you managed to use it correctly?

Because I’m trying it in Backtesting and the results are way worse than than expected with win rate at random level 50% but it returns the same prediction as in the test data which is way higher so I’m understanding what may be the problem 
(Btw Using Backtesting with the labels correctly return 99% win rate)

**Comment by hp260** [comment]
Good evening. 
I have a question about how to get the data？Because the data couldn't be found
